# Generated by Django 4.2 on 2023-05-03 05:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=50)),
                ('product_quentity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='prod_img/')),
                ('kg_or_ltr', models.CharField(choices=[('Kg', 'Kg'), ('Liter', 'Liter')], default='Kg', max_length=5)),
            ],
        ),
    ]
